language: java
dist: trusty
script: export MAVEN_OPTS="-Xmx1024m" && mvn clean -q cobertura:cobertura coveralls:report --quiet
addons:
  hostname: short-hostname
jdk:
  - oraclejdk8
notifications:
  email: false
